package rules;

import sbnz.vehicles.events.*;

rule "Battery fire alarm when temparature is above 125 C for 10 events in 90 seconds"
    when
        $e1: BatteryTemperatureEvent($vehicleId: vehicleId)
        Number(intValue >= 10) from accumulate(
            $e2: BatteryTemperatureEvent(
                this != $e1,
                temperature > 125,
                vehicleId == $vehicleId,
                this meets[90s] $e1
            ),
            count($e2)
        )
        not (BatteryTemperatureAlarm(vehicleId == $vehicleId))
    then
        insert(new BatteryTemperatureAlarm($vehicleId, $e1.getTemperature()));
end
